// <auto-generated />
namespace Bsa2er_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
<<<<<<< HEAD:Bsa2er MVC/Bsa2er MVC/Migrations/202007201048354_init.Designer.cs
    public sealed partial class init : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(init));
        
        string IMigrationMetadata.Id
        {
            get { return "202007201048354_init"; }
=======
    public sealed partial class bd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(bd));
        
        string IMigrationMetadata.Id
        {
            get { return "202007052232141_bd"; }
>>>>>>> 0ab8b865cd370de8f93605066c0634be5dff2eec:Bsa2er MVC/Bsa2er MVC/Migrations/202007052232141_bd.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
