// <auto-generated />
namespace Bsa2er_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
<<<<<<< HEAD:Bsa2er MVC/Bsa2er MVC/Migrations/202006232045242_v.Designer.cs
    public sealed partial class v : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v));
        
        string IMigrationMetadata.Id
        {
            get { return "202006232045242_v"; }
=======
    public sealed partial class programbody : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(programbody));
        
        string IMigrationMetadata.Id
        {
            get { return "202006241103480_programbody"; }
>>>>>>> 27b9de2dc54f61557737ae0f4e3197ad76cd7240:Bsa2er MVC/Bsa2er MVC/Migrations/202006241103480_programbody.Designer.cs
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
