// <auto-generated />
namespace Bsa2er_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class programbody : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(programbody));
        
        string IMigrationMetadata.Id
        {
            get { return "202006241103480_programbody"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
