// <auto-generated />
namespace Bsa2er_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Edit_exam_relation_with_program : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edit_exam_relation_with_program));
        
        string IMigrationMetadata.Id
        {
            get { return "202006211111522_Edit_exam_relation_with_program"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
