// <auto-generated />
namespace Bsa2er_MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_oneToOne_Relation_between_instructor_Student_and_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_oneToOne_Relation_between_instructor_Student_and_user));
        
        string IMigrationMetadata.Id
        {
            get { return "202006151227559_update_oneToOne_Relation_between_instructor_Student_and_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
